version: "3"

services:
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    restart: unless-stopped
    networks:
      - homelab_network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.focalboard.rule=Host(`focalboard.${SERVER_URL}`)"
      - "traefik.docker.network=homelab_network"
 
networks:
  homelab_network:
    external: true
    
